### ISSUE TITLE
Fancy Imagebar: where to store images

### ISSUE THREAD

**Issue by JustCarmen** [JustCarmen/fancy_imagebar#4]
Message originally posted here: https://github.com/JustCarmen/justblack/issues/12

As I have installed Fancy Imagebar, it is not clear to my where or how to store (in what folder on the server) pictures I want to display. I can nog find an instruction in the instructions for installing the module.

Please let me know....

**Comment by JustCarmen** [comment]
If you have installed the module you will find an extra menu option in the admin menu section for the Fancy Imagebar. There you can choose the images you want to show in the imagebar.

On the configuration page there is a help text available (click on the question mark)

You can also find some more information on my website: http://www.justcarmen.nl/fancy-modules/fancy-imagebar/

**Comment by FredFleury** [comment]
Carmen, thanks for your reply. I know about the extra menu option and the help text. Case is that after I have uploaded media and a ged file, i can see pictures in the regular slideshow of webtrees. But in the "gallery" of the menu section pictures are not displayed. So my question is what to do to get pictures into this gallery ?! By the way: a previous upload of media went wrong. But I can not remove the not found media from the listing in Media. After option Delete, text Delete completed is shown, but the media is stille mentioned in the listen. Hopefully you can help... Thanx Fred.
![fancy imagebar empty](https://cloud.githubusercontent.com/assets/7481755/5690776/60405cf0-98a2-11e4-93a8-fb29feaaaf09.png)

![not removable from media adm](https://cloud.githubusercontent.com/assets/7481755/5690777/65eb0fb0-98a2-11e4-8ce2-3be96ac3579c.png)

**Comment by JustCarmen** [comment]
Fred, you must know there is a difference between media (an image for instance) and a media-object. In your case the images don't exist on the server anymore but the media-object is still in the database. To break the link between the image and the media-object just click on 'Verwijder' on the right site of the screen.

Regarding the Fancy Imagebar:
There are a few conditions an image must meet before it can be used in the Fancy Imagebar.

* The extension must be 'jpg' or 'png'
* the image must be stored on the server (images linked from external sites can't be used)
* the image must be linked to an media-object.
* the image must be set as type is 'photo'

If I look at the last photo from your screenshot (which is partly visible) I can see it does meet the first three requirements. So I suspect the problem is the fourth one.

There are plenty of media-items which will meet the first three requirements, but those you don't want to have in the imagebar. For instance documents, newspapers, tombstones etc. There is only one way to know we are dealing with a photo and that is when the type is set to 'photo' on the media-object:

![10-1-2015 19-55-49](https://cloud.githubusercontent.com/assets/5641963/5692844/2b02f5fc-9906-11e4-83f0-c1a5f114d070.jpg)

**Comment by FredFleury** [comment]
Carmen, as an intuitive user, it thus was not clear to me that I have to upload pictures first via the personal records. I tried to work the other way around. Uploading and then linking. Gave anyhow problems. In the meantime I succeeded a I said via the personal records, works fine now. Thanks !

**Comment by JustCarmen** [comment]
Your welcome. And I will update the module information to make it more clear to future users. Thanks for your feedback.
