### ISSUE TITLE
Datatables warning: table id=image_block - Invalid JSON response

### ISSUE THREAD

**Issue by preceperi** [JustCarmen/fancy_imagebar#5]
When activating the module, I receive the following : 
Datatables warning: table id=image_block - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

I have <200 images. Some are JPG (rather than jpg) 

Per datatables.net/tb/1, attached is the screenshot of the Chrome debugger for Network.  

![capture - debug - network 2](https://cloud.githubusercontent.com/assets/10792271/5990752/4dd0a9b0-aa15-11e4-8833-a9586bae6092.png)

**Comment by JustCarmen** [comment]
The fact that some image are JPG shouldn't make any difference. The script searches images based on mime type rather then extension.

The screenshot doesn't give me any useful information about the JSON error.

To see the JSON error, install the "Firebug" plugin on firefox. Activate it (press F12). Select the "Net" tab, and then the "XHR" responses. Now refresh the page. You should be able to see an error message in the Firebug window.

**Comment by preceperi** [comment]
Hi JustCarmen. 

Ive exported the Firbug info into a HAR file available here >> https://www.dropbox.com/s/mdlmv3ewptn6c09/originofthekirbys.com%2B2015-02-15%2B17-55-22.har?dl=0
Let me know if this is what is needed

**Comment by JustCarmen** [comment]
Yes, this is useful information. I now can see the section where the script fails. The script tries to make a datatable with small thumbnails of the images that can be used in the Imagebar. In your case the creation of the thumbnails fails. Most likely you are missing the [GD Library](http://us2.php.net/manual/en/ref.image.php) in your php configuration.
You could check if this is the case by going into your webtrees administration and click in the menu in the Administration section on 'PHP Information'. Search for GD Support. It must be enabled. If you can not find this section or it stated as disabled then you need to ask your ISP to turn it on.

On the other hand I need to fix the script to catch a failure like this and provide some kind of an error message.

**Comment by preceperi** [comment]
Thanks JustCarmen. 

I have GD Support enabled (GD Version bundled (2.1.0 compatible)) but no specific GD library.

As it happens, I noticed this afternoon that if I limit myself to display only first 5 or 15 images, I do not see the error. ON further investigation, I noticed that some of my images are missing. I will remove the broken links and see if that addresses the issue as well. 

Cheers.

**Comment by JustCarmen** [comment]
Now we know you have GD Support I think you are on the right track. The script pulls the media object information from the database. Second it search for the corresponding images on the server and then it makes small thumbnails from these images.

But what bothers me is that the script does check the existence of an image on the server before it tries to create the thumbnail. So if some of your links are broken these media objects would be simply ignored. But let me know your findings, then we will see what else we can do.

**Comment by preceperi** [comment]
Hi JustCarmen. apologies for the delay to get back to you. There were a lot of links..

I have removed the broken file links but the problem remains. 

I have uploaded the latest JSON file to:
https://www.dropbox.com/s/k66poocwvni6aef/originofthekirbys.com_JSON_150315?dl=0

Cheers

**Comment by JustCarmen** [comment]
Check out the bugfix to see if it helps.

Be sure you download from the support-1.6.2 branch.

https://github.com/JustCarmen/fancy_imagebar/blob/support-1.6.2/module.php

Let me know if this solves your issue.

**Comment by preceperi** [comment]
Hi Carmen. No joy Im afraid

https://www.dropbox.com/s/xojge7w081layfq/originofthekirbys.com_JSON_150315a?dl=0

**Comment by JustCarmen** [comment]
I can't open your last file. But I have been able to check it with notepad++ and I can read the error message, which is all I need.

This is your last error message:
>><br>ERROR 2: Division by zero<br>0 Error occurred on line <b>390</b> of file <b>module.php</b> in function <b>FancyThumb</b><br>1 called from line <b>120</b> of file <b>module.php</b> in function <b>displayImage</b><br>2 called from line <b>106</b> of file <b>module.php</b> in function <b>load_json</b><br>3 called from line <b>154</b> of file <b>module.php</b> in function <b>modAction</b><br>4 called from line <b>33</b> of file <b>module.php</b><br><br>ERROR 2: Division by zero<br>0 Error occurred on line <b>392</b> of file <b>module.php</b> in function <b>FancyThumb</b><br>1 called from line <b>120</b> of file <b>module.php</b> in function <b>displayImage</b><br>2 called from line <b>106</b> of file <b>module.php</b> in function <b>load_json</b><br>3 called from line <b>154</b> of file <b>module.php</b> in function <b>modAction</b><br>4 called from line <b>33</b> of file <b>module.php</b><br><br>ERROR 2: Cannot modify header information - headers already sent by (output started at /home/y02wxtsb/public_html/includes/session.php:311)<br>

I think you didn't upload the right file, or something went wrong on upload.The line numbers from the error message above don't match with the version of the file I posted earlier today. The function FancyThumb starts on line 412 so you can't get an error on line 390 and 392 for that function.

In my previous post I gave you a link. Right click on it and choose link save as to save the file to your computer. Upload the file to your webtrees installation in the folder modules_v3/fancy_imagebar. Overwrite the existing module.php file.

Try it again and let me know the results.

**Comment by preceperi** [comment]
Hi Carmen. I have reinstalled the latest version. I also replaced style.css and style.js 

The good news is the error references are new. The bad news is they remain

Thoughts?

ERROR 2: Division by zero
0 Error occurred on line 428 of file module.php in function FancyThumb
1 called from line 503 of file module.php in function GetFancyImageBar
2 called from line 558 of file module.php in function getMenu
3 called from line 427 of file navmenu.php in function getModuleMenus
4 called from line 91 of file functions.php in function getJLNavMenu
5 called from line 116 of file header.php in function require
6 called from line 163 of file Page.php in function pageHeader
7 called from line 85 of file index.php

ERROR 2: Division by zero
0 Error occurred on line 431 of file module.php in function FancyThumb
1 called from line 503 of file module.php in function GetFancyImageBar
2 called from line 558 of file module.php in function getMenu
3 called from line 427 of file navmenu.php in function getModuleMenus
4 called from line 91 of file functions.php in function getJLNavMenu
5 called from line 116 of file header.php in function require
6 called from line 163 of file Page.php in function pageHeader
7 called from line 85 of file index.php

**Comment by JustCarmen** [comment]
This sounds more logic.

But I am really stuck here. The images do exist on the server. The image are all from the type "photo" and they have an extension of "jpg" or "png". These checks were all done before this function runs. Images that don't match these criteria are left out.

The script stops at the moment it needs the image size. It can't retrieve the width and the height of one or more of the images for some reason. From here it is hard to tell what the problem is, because it must be something on your side. I can't even reproduce the error, which makes it really hard to solve.

Until now I have tried some things which I though might solve the problem, but it doesn't help you much further.

The only way to help you out is that you give me full access to your webtrees installation (as admin) and to the server (ftp-access) so I can investigate the problem more efficiently.

You can [contact me](http://www.justcarmen.nl/contact/) directly with the details. Don't reply on this message, because your answer will be automatically posted here.

**Comment by JustCarmen** [comment]
By giving me access to your site I was able to locate the problem. It turns out that some of your image files are corrupt. Locating and removing these images solved the problem.

I will look into my code to see if I can implement a kind of fallback for cases like these.

**Comment by smacm** [comment]
I'm having what seems to be a very similar issue.  Whenever I click on the "Media" link in the administration console I get the "datatables invalid JSON response" error message:
![invalid json response error message](https://cloud.githubusercontent.com/assets/5835570/8268338/1fd5e4be-1750-11e5-8690-4fdeff7d1876.PNG)
The javascript error message is:
![javascript console error message](https://cloud.githubusercontent.com/assets/5835570/8268341/31d19cee-1750-11e5-8a88-1565bce22c03.PNG)
and the offending javascript code is:
![javascript function error](https://cloud.githubusercontent.com/assets/5835570/8268345/3e657afc-1750-11e5-8f81-73b898dd9039.PNG)

I do have GD extensions enabled in PHP.
Any suggestions for how to clear this error?

Thanks,
Steve

**Comment by smacm** [comment]
Note:  Restarting Chrome cleared the error I described above.
